name: Notify Google Chat on new Github Pull Request 
on:
  pull_request:
    types:
      - review_requested
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cardsV2": [
                {
                  "cardId": "unique-card-id",
                  "card": {
                    "header": {
                      "title": "Nouvelle PR",
                      "subtitle": "${{ github.event.pull_request.title }}"
                    },
                    "sections": [
                      {
                        "widgets": [
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "PERSON"
                              },
                              "text": "${{ github.event.pull_request.user.login }}"
                            }
                          },
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "BOOKMARK"
                              },
                              "text": "${{ github.event.repository.name }}"
                            }
                          },
                          {
                            "buttonList": {
                              "buttons": [
                                {
                                  "text": "OPEN PR",
                                  "onClick": {
                                    "openLink": {
                                      "url": "${{ github.event.pull_request.html_url }}"
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }'
