name: Notify Google Chat on Pull Request merge
on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Git PR Details
      run: |
          echo "PR title: ${{ github.event.pull_request.title }}"
          echo "PR creator: ${{ github.event.pull_request.user.login }}"
          echo "PR link: ${{ github.event.pull_request.html_url }}"
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "PR merged",
                          "subtitle": "${{ github.event.pull_request.title }}"
                      },
                      "sections": [
                          {
                              "widgets": [
                                  {
                                     "keyValue": {
                                          "topLabel": "Merged by",
                                          "content": "${{ github.event.pull_request.merged_by.login }}"
                                      },
                                   }
                              ]
                          }
                      ]
                  }
              ]
          }'
