name: Notify Google Chat on Pull Request merge
on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Git PR Details
      run: |
          echo "PR title: ${{ github.event.pull_request.title }}"
          echo "PR creator: ${{ github.event.pull_request.user.login }}"
          echo "PR link: ${{ github.event.pull_request.html_url }}"
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cardsV2": [
                {
                  "cardId": "unique-card-id",
                  "card": {
                    "header": {
                      "title": "<font color=\"#1a7f37\">PR merged</font>",
                      "subtitle": "${{ github.event.pull_request.title }}"
                    },
                    "sections": [
                      {
                        "widgets": [
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "PERSON"
                              },
                              "text": "${{ github.event.pull_request.user.login }}"
                            }
                          },
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "BOOKMARK"
                              },
                              "text": "${{ github.event.repository.name }}"
                            }
                          },
                          {
                            "buttonList": {
                              "buttons": [
                                {
                                  "text": "OPEN PR",
                                  "onClick": {
                                    "openLink": {
                                      "url": "${{ github.event.pull_request.html_url }}"
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }'
